version: '2'

services:
  php:
    depends_on:
       - db
    image: php:5.6.30-fpm
    volumes:
      - .:/var/www
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes_from:
      - php
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
  db:
    image: mysql:5.7
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
  composer:
    restart: 'no'
    image: composer/composer:php5
    command: install
    working_dir: /var/www/
    volumes_from:
      - php